# L5R 5E — Wedding at Kyotei Castle (.arc)
# Structure of the 2018 L5R Gen Con adventure (FFG, 2019). The GM narrative,
# read-aloud text, and handouts live in l5r5e-0.5-wedding-kyotei.lore; the cast
# adversaries in l5r5e-0.5-wedding-kyotei-cast.ttrpg; the seven pregenerated PCs
# in l5r5e-0.5-wedding-kyotei-pregens.actor. NPC carets resolve to those DEFs.

ARC "wedding-kyotei-castle" EXTENDS "l5r5e" {
    NAME "Wedding at Kyotei Castle"
    VERSION "0.5.3"
    SPEC_VERSION "0.5"
    SYSTEM "l5r5e"
    SOURCE "Wedding at Kyotei Castle: The 2018 L5R Gen Con Adventure (Fantasy Flight Games, 2019)"
    LEAD_WRITER "Katrina Ostrander with Alexis Dykema"
    DESCRIPTION "When inauspicious signs threaten to derail a crucial wedding between the Crane and Phoenix Clans, it falls to a group of young samurai to choose whether to see the match through or call it off—resulting in great loss of face for the Crane and Phoenix Clans. Certainly, not all of the guests are here to congratulate the honored couple.\n\nIn Wedding at Kyotei Castle, the PCs must choose whether to defend or disrupt the marriage between Tsume Takashi and Shiba Isuyo, which would seal a strategic alliance between the Crane and Phoenix clans. Over the course of four scenes, the PCs witness the stakes of the conflict in the Kintani, the Golden Valley, including the cost the peasants must bear while samurai squabble over the land. No sooner do the PCs arrive at Kyotei Castle than they discover that the castle shrine has been blighted by death, and the wedding ceremony must be moved to a local shrine on the outskirts of the castle.\n\nAs they investigate whether the cause of the ill omen is supernatural or mundane, they stumble across a conspiracy to install the lost heir of a Lion Clan vassal family as daimyō of the castle. But will the PCs attempt to collaborate with the conspirators or thwart them? Their choices will lead them to the local shrine or the walls of Kyotei Castle, where battles for the heart of the daimyō and the valley itself will be waged."

    THEMES ["Choice and consequence", "Duty versus compassion", "The cost peasants bear while samurai squabble", "Old blood and restless ghosts", "A political marriage as a battlefield"]

    TONE "Courtly intrigue turning to open violence; a murder mystery beneath a wedding"
    PLAYER_COUNT "Six PCs (school rank 1; group rank 6), using the seven pre-generated characters"
    SUMMARY "To ensure peace in the Golden Valley, a young daimyō of a Crane Clan vassal family, Tsume Takashi, is to be wed to Phoenix Clan bushi Shiba Itsuyo, daughter of the lord of Nikesake, a neighboring Phoenix Clan city. This is purely a political match, and in fact, the couple has met only once before, when the engagement was sealed. There is no love between them—at least, not yet, anyway—but such is expected in Rokugan. Moreover, Takashi's heart is still broken by the geisha Reika from Pine House, who manipulated Takashi into a relationship so that she could gain access to the inner castle at Kyotei and murder his father, Tsume Retsu, in his very bedchambers. Reika was carrying out her family's revenge, having learned that she was truly the last heir to the Damasu family and would have been the rightful lord of the castle—had it not been for Retsu's savagery.\n\nReika escaped the justice of the Emerald Magistrates with the help of a local rōnin named Itto. The Scorpion Clan's spy network knows the history of Kyotei Castle and discovered Reika's secret, which they plan to use to deprive the Crane Clan of their castle. By putting the Crane on their back foot and preventing an alliance between the Crane and Phoenix clans, the Scorpion ensure their dominance in the Imperial Capital. To further this goal, a Shosuro actor named Yu has been masquerading as a rōnin. She helped Reika appeal to the Lion Clan and be adopted as Damasu no Akodo Maeda, and the last surviving heir of the Damasu family. Because vassal family names are not often used outside the clan, she is only ever introduced to others as Akodo Maeda, allowing her to keep her Damasu identity hidden until she needs to leverage it.\n\nThe Lion Clan does not know of Maeda's role in the murder of Tsume Retsu, nor do they realize she plots to kidnap and marry Takashi, rekindling his love for her to convince him to marry her. If she succeeds, this would force his sworn samurai to join her side or commit seppuku in protest. If that doesn't work, she'll kill him and as many of his samurai as possible, blame the massacre on rōnin, and leave the castle open to a Lion Clan attack.\n\nIt's up to the PCs to decide whether they should thwart Maeda or aid her. The fate of Kyotei Castle—and of Toshi Ranbo—hangs in the balance. If the castle falls, the Crane Clan's land-based supply lines to Toshi Ranbo could be cut off entirely, forcing them to conduct dangerous river traffic. And that shift in power could prove a golden opportunity for the other Great Clans."

    # ─────────────────────────────────────────────
    # SCENE STRUCTURE
    # ─────────────────────────────────────────────
    PARTS {
        PART 0 "The Adventure Begins" {
            SCENES ["Starting the Scenario"]
            DESCRIPTION "Before play begins, welcome everyone to the game. Help the players choose characters, answer questions about the system or setting, and identify to yourself which players are likely to be strong personalities and who might need encouragement to get involved and let their character shine. After each player has selected one pre-generated character, have them read their ninjō and giri privately. Once you've had a chance to answer any last-minute questions and arrange the play area, start the scenario by reading the following aloud:\n\nRokugan is a land of choice and consequence—you are samurai serving one of the Great Clans, and your path is one that walks the line between life and death, duty and honor, justice and compassion. Bushi, or warriors, walk the path of violence; courtiers walk the path of diplomacy; shugenja walk the path of the spirits; and monks walk the path of enlightenment.\n\nAn informal war rages between the Lion and Crane clan from the Osari Plains to the City of Toshi Ranbo, cutting a swathe of devastation across northeastern Rokugan. This so-called \"border conflict\" has already led to the slaying of the Lion Clan Champion at the hands of the Crane Clan Champion, the deaths of hundreds of samurai, and countless more ashigaru and peasants killed, lost, or displaced.\n\nAnd so, a wedding sealing a martial alliance between a vassal family of the Crane Clan and neighboring family of the Phoenix Clan threatens to become another battlefield. The ceremony is to be held at the Crane lord's castle at Kyotei, one of the first Lion castles to fall in the conflict, and the Lion have never forgotten this bruise to their pride. You are one of the few esteemed guests, carefully chosen to represent your clan owing to your history with the bride or groom.\n\nAdditionally, read or paraphrase the following aloud:\n\nEach of you hails from a different Great Clan, and as such, your lord has their own interests in sending you to Kyotei Castle—interests that may might lead you into conflict with those of the other player characters. This means that some PCs might be working against each other by the end of the scenario, but not all players enjoy this level of competitiveness in their RPGs. As a group, decide whether you want to allow party conflict. Write down your preference on a scrap of paper and give it to me (the GM). If anyone isn't comfortable with a party conflict game, we'll run without party conflict.\n\nIf everyone chooses to enable party conflict, PCs will be allowed to try to undermine each other directly, fight each other, and might even becoming each other's villains before the scenario is over. The scenario works either way, so vote for the one you'd prefer."
        }
        PART 1 "Scene 1: The Price of War" {
            SCENES ["The Price of War"]
            DESCRIPTION "The dirt road through the Golden Valley was once known for its gentle hills, immaculately kept inns, and friendly merchants, but in these troubled times, travelers are as likely to meet with bandits as they are fellow samurai. Crane and Lion clan forces clash in the nearby foothills of Toshi Ranbo, and ragged mercenary soldiers look to the supply trains that flow between the palaces of the Crane and Kyotei Castle for supplemental recompense. There is safety in numbers, and as fate would have it, you find yourself journeying alongside others who proudly wear their wakizashi and clan crests.\n\nBelow the ridge, the PCs happen upon a scene far too common in war: a gang of ruffians on horseback, clad in dinted lacquered armor and wielding spears, whooping and circling around a haggard-looking peasant family of three. They shout, \"Your lord sent us to collect the taxes early! Pay up—or pay with your lives for your insolence!\" The peasants resist, claiming they have nothing left, but the bandits are not convinced, and they draw their swords. \"Don't hold out on us, we know you wouldn't have left your family fortunes behind!\"\n\nAt this point, the PCs can intervene and challenge the validity of the bandits' claims. A TN 3 (Air 2, Earth 4) Sentiment check confirms that these ruffians are bluffing—they are but common highway thieves now, even if they were once legitimate mercenaries. A TN 3 (Fire 2, Void 4) Labor check reveals that the villagers have nothing on their persons to offer the brigands other than their meager lives."
        }
        PART 2 "Scene 2: Ill Omens" {
            SCENES ["Arrival at Kyotei Castle", "Kyotei Shrine"]
            DESCRIPTION "A dozen spear-wielding guards look down upon you from the walls while the great gate is opened, and two more soldiers approach you with a bow of respect. They politely request to inspect your traveling papers giving each of you an appraising look. No more than another minute passes when an old woman appears, bowing deeply to all of you in turn. She introduces herself as Ojuno, personal servant to Lord Tsume, and leads you through the gate to the courtyard and then an indoor reception hall. As you find your seats, the sound of rushing footfalls cascades up and down the hallways, punctuated by shouts and fearful voices. Ojuno remains completely poised despite the disturbances all around you, and serves tea from a tray proffered by a younger servant.\n\n\"We ask your humble forgiveness, honored samurai, but I am afraid your arrival comes at an ill hour. Lord Takashi would have come to greet you himself were it not for the most unfortunate of calamities to have befallen our sacred shrine.\"\n\nAt this point, the PCs may politely inquire as to nature of the calamity. Due to their personal background with Takashi—but also the PCs would inevitably find out through rumor otherwise—Ojuno summarizes the recent events:\n\nThis morning, a flock of cranes was found dead and strewn about the grounds of the castle shrine.\n\nThe dead flock is an extremely grave omen, casting a dark cloud of doubt over the wedding proceedings. Are the kami or ancestors themselves displeased with the match?\n\nThe wedding would have been postponed until the proper auguries could be completed were the alliance not of such a vital military importance. But with the Lion Clan army still at the doorstep of Toshi Ranbo, the union must be sealed as soon as possible.\n\nBecause the entire shrine has been made unclean with the stain of death, Head Priest Tsume Yemon has had no choice but to send word to the nearby Golden Valley Shrine to request that they move the ceremony there.\n\nIf the PCs have investigated the shrine thoroughly, they should suspect that the cranes were killed by human hands, that someone impersonated Satuski to plant them in the shrine, and that the ghosts of the castle had nothing to do with the atrocity but are no less pleased."
            HANDOUTS true
        }
        PART 3 "Scene 3: Feast and Famine" {
            SCENES ["The Feast", "Investigation and Accusation"]
            DESCRIPTION "That evening, a shared meal in the Tsume main courtroom with all the wedding guests provides a chance to talk to the other guests, and thereby discern the alibis as well as possible motives of those in attendance. The dinner also represents a chance to learn more about the couple, as well who stands or gain or lose by the marriage falling through. This will force the players to decide for themselves whether they want to see this marriage through or break it—and in so doing, the alliance between the Crane and Phoenix. If the players have all chosen to work together, then they are trying to see the marriage through. But if they are playing a game with party conflict enabled, this is also a chance for the player characters to gather allies and advance their agendas in secret.\n\nIf the PCs succeeded at investigating the shrine, they should be on the lookout for someone capable of poisoning and impersonating Satsuki. They might set their sights on the Scorpion, Soshi Ozuru (and not without reason), but if they learn that Doji Kuzunobu is a former member of the Kitsune family (who, say certain whispered folktales, include shape-changing spirits among their number), they might be suspicious of him as well.\n\nYet, with careful investigation, their sights should settle on Ide Torao, who doesn't quite fit the role he supposedly fills. Although they do not have the legal right to arrest him themselves, they can potentially convince Tsume Takashi to exercise his authority instead. Due to the nature of the Rokugani justice system, the PCs can simply accuse Ide Torao of a crime on the strength of their honor, and he will be taken into custody. Doing so rewards the PCs with 6 glory each.\n\nIf the PCs also manage to uncover Akodo Maeda's plot, they might even be able to confront her at the dinner (in which case, the final scene changes from Scene 4a: The Wedding, on page 25 to Scene 4b: The Siege, on page 27)."
        }
        PART 4 "Scene 4a: The Wedding" {
            SCENES ["Procession to the Golden Valley Shrine", "Showdown at the Shrine"]
            DESCRIPTION "Regardless of whether the PCs succeeded in arresting Ide Torao for his role in the death of the cranes and the desecration of the shrine, the PCs have a wedding to attend the following day.\n\nThe PCs make the short journey to the Golden Valley Shrine on foot, in ceremonial clothing. They may carry their wakizashi, but are forbidden by custom from having heavier weapons or armor. If a PC wishes to find a clever means to smuggle equipment to the wedding for any reason (or arrange for it to be delivered, or hide it in the shrine beforehand), the GM should allow them to do so without a check provided they can offer a reasonable plan, but the PC must forfeit 3 honor. Especially obvious efforts, like trying to arrive in full armor, require the character to forfeit 3 glory as well, and lead to the PC being ejected from the wedding party and sent back to the castle.\n\nBut the voice didn't come from the bandits—it came from Akodo Maeda, who has stopped among the procession and has stepped up to grab Takashi by the collar, her katana drawn. \"Takashi-san, I have come to rescue you from your plight. It is our passion that burns bright—that demands to be recognized. Itto carried me from this castle as a child when Tsume Retsu slaughtered my family, but now I return as a warrior to reclaim it! Marry me, and right the wrongs that your father set into motion so many years ago. Let the Damasu and Tsume families be united in reconciliation, that no more bloodshed may stain this land.\"\n\nIf the PCs spoke to Takashi about his problem (or rather, his \"fictional character's\" problem) and convinced him to honor his duty to his father and his clan, he refuses Maeda's demands. If none of the PCs convinced Takashi of the importance of his marriage to Itsuyo or they convinced him to follow his heart, he defaults to siding with Maeda, his erstwhile lover. Takashi has no desire to be a true ruler, after all. Maeda solves many problems for him at once, for the low price of being a traitor to a lord he had no desire to serve."
        }
        PART 5 "Scene 4b: The Siege" {
            SCENES ["Defend the Castle", "Attack the Castle"]
            DESCRIPTION "If the PCs challenged Maeda openly at the feast, then as the sun crests over the forest (well before the hour of the wedding), they awaken to alarm bells and panic in the castle. Read aloud or paraphrase the following:\n\nThe castle is in a frenzy, alarm bells ringing and ashigaru milling about as General Shizuma barks orders from the battlements. As you rub your eyes, you suspect that the worst has happened: Damasu no Akodo Maeda has returned to take her castle through force of arms. War's shadow looms long over the Golden Valley once again.\n\nGeneral Shizuma is available to answer questions and direct the PCs if needed. He invites them to the battlements with him, as they are distinguished representatives of the Crane's allies and formidable fighters or investigators in their own right. He also arms any PCs with appropriate equipment, described below:"
        }
        PART 6 "Resolution: The Fate of the Valley" {
            DESCRIPTION "If a group of the PCs stops Maeda from kidnapping and marrying Takashi, then the wedding party returns triumphant, with Tsume Takashi riding a magnificent steed and his new bride Itsuyo riding behind him. The rest of the wedding party follows, visibly relieved. If Maeda is dead or in bonds, she will be brought on a horse ridden by Kotonoha, staying some distance behind the main party.\n\nIf time remains, the GM can ask the players what their characters do in the wake of these events, and narrate some thoughts about what their choices might mean for their personal stories.\n\nIf Maeda is killed, the Damasu ghosts of the castle all cry out at once in agony—they will be eternally bound to the castle, unable to move on to the afterlife. Spiritually sensitive characters are stuck with a feeling of nausea. If Takashi was still undecided, he falls upon Maeda's corpse, weeping inconsolably. General Shizuma or Captain Kotonoha (if either lives) thank the PCs for their service, then grimly set about removing all evidence of the entire affair."
        }
    }

    # ─────────────────────────────────────────────
    # LOCATIONS
    # ─────────────────────────────────────────────
    LOCATIONS {
        #94zzQoD5HrLMGw3onxEIw8 ^"Kyotei Castle" DEF {
            TYPE "Castle"
            REGION "The Kintani (Golden Valley)"
            DESCRIPTION "Twenty years ago, the Damasu family of the Lion Clan ruled the Golden Valley from their stronghold at Kyotei Castle, which lies along a merchant's road between Otosan Uchi and Toshi Ranbo. The castle and the nearby town of Chikuzen are strategically located between Lion, Crane, and Phoenix lands, making the castle one of many witnesses to bloodshed over the last several centuries.\n\nTsume Retsu, a vassal to the Doji family of the Crane Clan, conquered Kyotei Castle by force of arms. Lord Damasu Kojima and the entirety of the Damasu family (a vassal family sworn to the Akodo family of the Lion Clan) fell in battle. After the dust had settled, the Doji family allowed Retsu to hold the castle as its new lord. However, the Doji had not ordered Retsu to take such drastic action, and so the Doji's diplomatic arm found itself busy trying to hold back the furious vengeance of the Lion Clan and assuage fears of further aggression on the part of Lord Tsume toward the Phoenix.\n\nRumors have always swirled that the castle is haunted by the Lions who fell there. Perhaps it is cursed, for after seventeen years of ruling the Golden Valley from Kyotei Castle, Lord Retsu was discovered dead in his very chambers, apparently a victim of murder. A search went out for the culprit, and after weeks of fruitless investigation, a castle guard was charged with the lord's murder and executed."
            NPCS [#UH9YhxLjjeoOde71MqOXv0 ^"Tsume no Doji Takashi", #t6dYqjCmp3px4f5605LRDG ^"Nasu no Shiba Shizuma", #Dvw1Lu2m7QpqDF0a5A9W1j ^"Tsume Kotonoha", #zq8m9duYS3bWSkcX7hAqSc ^"Tsume Yemon"]
        }
        #LPehK6XmzxQ67ruzKA2xQv ^"The Kintani" DEF {
            TYPE "Region"
            DESCRIPTION "The dirt road through the Golden Valley was once known for its gentle hills, immaculately kept inns, and friendly merchants, but in these troubled times, travelers are as likely to meet with bandits as they are fellow samurai. Crane and Lion clan forces clash in the nearby foothills of Toshi Ranbo, and ragged mercenary soldiers look to the supply trains that flow between the palaces of the Crane and Kyotei Castle for supplemental recompense. There is safety in numbers, and as fate would have it, you find yourself journeying alongside others who proudly wear their wakizashi and clan crests."
        }
        #KUxn7am8ARCWzuavYshnaT ^"Kyotei Shrine" DEF {
            TYPE "Temple"
            DESCRIPTION "The castle shrine is small, large enough to hold the name plaques of a single family and a vessel to house a single kami. Tsume Yemon, the head priest, has gone into the surrounding forest in order to purify himself and request the forgiveness of the local spirits. And so, it is up to the three shrine keepers to clean up the mess and begin preparations for reconsecrating the shrine. When the PCs arrive, they see two of the shrine keepers are pouring water over the gravel to clean the blood from the ground, while a third off to one side is on her hands and knees scrubbing a stepping stone. Upon passing under the threshold torii gate to the shrine, every character can feel a chill down their spine and the hair on the back of their necks standing up. Something is very wrong here, spiritually."
        }
        #RyCnU0wTyEWKSadvTr3PEY ^"Golden Valley Shrine" DEF {
            TYPE "Temple"
            DESCRIPTION "The local shrine on the castle's outskirts to which the wedding ceremony is moved after the desecration of Kyotei Shrine; site of the Scene 4a showdown."
        }
        #YTlsDZDisT7mKwEzYzF6hI ^"Chikuzen" DEF {
            TYPE "Town"
            DESCRIPTION "The town near Kyotei Castle, home to the Pine House geisha establishment where the infant Damasu heir was hidden and raised as Reika."
        }
        #hzjWLAtaxvQabWq4jHbpzC ^"Pine House" DEF {
            TYPE "Building"
            SETTLEMENT "Chikuzen"
            DESCRIPTION "The geisha house where Damasu no Akodo Maeda was raised and trained as the geisha Reika, and where she seduced Tsume Takashi to gain access to the castle."
        }
        #289nlwQHoXWSf0lb3YLQ3h ^"Nikesake" DEF {
            TYPE "City"
            DESCRIPTION "A neighboring Phoenix Clan city, home of the bride Shiba Itsuyo and her father Shiba Katsuda, once relieved from siege by Tsume Retsu."
        }
        #LSrpK8vRPPLpw9Q29KOqMt ^"Toshi Ranbo" DEF {
            TYPE "City"
            DESCRIPTION "The contested city at the heart of the Crane–Lion border conflict; Kyotei Castle guards the Crane's land-based supply lines to it."
        }
    }

    # ─────────────────────────────────────────────
    # CAST (resolve to l5r5e-0.5-wedding-kyotei-cast.ttrpg)
    # ─────────────────────────────────────────────
    KEY_NPCS {
        ANTAGONISTS [#y8CEub8orO5qjMqJ0JRyAc ^"Damasu no Akodo Maeda", #ZZIF2kGdhvsJPaUw30b9A5 ^"Itto", #ZXcZtrUYFjOWWeCgYA8iKb ^"Ide Torao aka Shosuro Yu", #Iw3BhfwuAQXhqNPnceDSGI ^"Soshi Ozuru"]
        CRANE [#UH9YhxLjjeoOde71MqOXv0 ^"Tsume no Doji Takashi", #t6dYqjCmp3px4f5605LRDG ^"Nasu no Shiba Shizuma", #Dvw1Lu2m7QpqDF0a5A9W1j ^"Tsume Kotonoha", #zq8m9duYS3bWSkcX7hAqSc ^"Tsume Yemon", #jknaRUzeg6hz5t8D4apE5R ^"Doji Kuzunobu"]
        PHOENIX [#GgTX6wKxW4cE4jNBHylppy ^"Shiba Itsuyo", #7rDy9sSDbpM8oNAkkGCuce ^"Shiba Katsuda", #cIf2Uo7ewkaZZlABmFdShI ^"Lady Chisei", #QaRk93hHlGWVRmVtRrBms5 ^"Asako Maezawa"]
    }

    # ─────────────────────────────────────────────
    # PREGENS (resolve to l5r5e-0.5-wedding-kyotei-pregens.actor)
    # ─────────────────────────────────────────────
    PARTY {
        PREGENS [#Vsvs3jlQI5Hh8XeoN1kLE3 ^"Bayushi Hibiki", #JQjUmxaMDWvsKGwAeu0ayD ^"Kaito Natsuyuki", #Rl6BFMrYEMEyaqCcRUm2Pg ^"Kakita Hikaru", #gfE4VVJHOHIuaf1UZ6XLKp ^"Kitsu Kohaku", #GrRQkuGG0fOpQkCsVPo3Ga ^"Kitsuki Sora", #y6vPP6stQ7khksNdGTRbsj ^"Utaku Azami", #uasvsqsnjLLL5wAlcRPMlC ^"Yasuki Toru"]
    }
}
